class LaTeXGenerator:
    def render_report(self, project: dict, sections: list[dict], references_bib: str = "") -> str:
        body = "\n\n".join(section["content"] for section in sections)
        return rf"""
\documentclass[12pt,a4paper]{{report}}
\usepackage[margin=1in]{{geometry}}
\usepackage{{setspace}}
\usepackage{{graphicx}}
\usepackage{{hyperref}}
\usepackage{{titlesec}}
\onehalfspacing

\title{{{project["title"]}}}
\author{{Generated by ReportAI}}
\date{{\today}}

\begin{{document}}
\maketitle
\pagenumbering{{roman}}
\chapter*{{Certificate}}
This is to certify that the project report titled \textbf{{{project["title"]}}} was prepared according to the selected university template.

\chapter*{{Declaration}}
The content in this report is generated as an academic draft and should be reviewed by the student and supervisor.

\chapter*{{Acknowledgement}}
The author expresses sincere gratitude to the institution, guide, and collaborators.

\tableofcontents
\listoffigures
\listoftables
\clearpage
\pagenumbering{{arabic}}

{body}

\bibliographystyle{{IEEEtran}}
\bibliography{{references}}
\end{{document}}
""".strip()

    def render_references(self, entries: list[str]) -> str:
        return "\n\n".join(entries)
