import type { Project, QualityScore } from "@/lib/types";

export const reportSections = [
  "Abstract",
  "Acknowledgement",
  "Introduction",
  "Literature Review",
  "System Analysis",
  "System Design",
  "Methodology",
  "Implementation",
  "Testing",
  "Results",
  "Conclusion",
  "Future Scope",
];

export function generateLatex(project: Project, answers: Record<string, string>) {
  const answerText = Object.entries(answers)
    .filter(([, value]) => value.trim())
    .map(([key, value]) => `${key.replaceAll("_", " ")}: ${value}`)
    .join("\\\\\n");

  return String.raw`\documentclass[12pt,a4paper]{report}
\usepackage[margin=1in]{geometry}
\usepackage{setspace}
\usepackage{hyperref}
\onehalfspacing
\title{${project.title}}
\author{Generated by ReportAI}
\date{\today}
\begin{document}
\maketitle
\tableofcontents

${reportSections
  .map(
    (section) => String.raw`\chapter{${section}}
${project.title} is an academic project in the ${project.domain} domain. ${project.description}

\section{Project Evidence}
${answerText || "Project-specific evidence should be added through the questionnaire."}`,
  )
  .join("\n\n")}

\bibliographystyle{IEEEtran}
\bibliography{references}
\end{document}`;
}

export function analyzeQuality(latex: string, referenceCount: number): QualityScore {
  const wordCount = latex.split(/\s+/).filter(Boolean).length;
  const technicalDepth = Math.min(95, Math.max(45, Math.round(wordCount / 25)));
  const citationQuality = referenceCount > 0 ? 86 : 45;
  const formattingQuality = latex.includes("\\chapter") && latex.includes("\\tableofcontents") ? 90 : 58;
  const grammar = 84;
  const readability = 82;
  const overall = Math.round((technicalDepth + citationQuality + formattingQuality + grammar + readability) / 5);
  const suggestions = [];

  if (wordCount < 2500) suggestions.push("Expand methodology, testing, implementation, and result analysis.");
  if (referenceCount === 0) suggestions.push("Add academic references and cite them inside chapters.");
  if (!latex.includes("\\includegraphics")) suggestions.push("Add UML, flowchart, architecture, or result diagrams.");

  return {
    grammar,
    readability,
    technical_depth: technicalDepth,
    formatting_quality: formattingQuality,
    citation_quality: citationQuality,
    overall,
    suggestions,
  };
}
