import type { Project, QualityScore } from "@/lib/types";
import type { Question } from "./questionnaire";
import { getOpenAiApiKey } from "@/lib/utils";

export const reportSections = [
  "Abstract",
  "Acknowledgement",
  "Introduction",
  "Literature Review",
  "System Analysis",
  "System Design",
  "Methodology",
  "Implementation",
  "Testing",
  "Results",
  "Conclusion",
  "Future Scope",
];

// Helper function to check if a string is considered "NIL" or equivalent empty answer
export function isNilAnswer(value: string): boolean {
  const clean = value.trim().toLowerCase();
  return (
    clean === "" ||
    clean === "nil" ||
    clean === "none" ||
    clean === "nothing" ||
    clean === "n/a" ||
    clean === "na" ||
    clean === "not applicable" ||
    clean === "null" ||
    clean === "no" ||
    clean === "none." ||
    clean === "nil."
  );
}

// Fallback Static LaTeX generator
export function generateLatex(project: Project, answers: Record<string, string>) {
  const answerText = Object.entries(answers)
    .filter(([, value]) => value && !isNilAnswer(value))
    .map(([key, value]) => `${key.replaceAll("_", " ")}: ${value}`)
    .join("\\\\\n");

  return String.raw`\documentclass[12pt,a4paper]{report}
\usepackage[margin=1in]{geometry}
\usepackage{setspace}
\usepackage{hyperref}
\onehalfspacing
\title{${project.title}}
\author{Generated by ReportAI}
\date{\today}
\begin{document}
\maketitle
\tableofcontents

${reportSections
  .map(
    (section) => String.raw`\chapter{${section}}
${project.title} is an academic project in the ${project.domain} domain. ${project.description}

\section{Project Evidence}
${answerText || "Project-specific evidence should be added through the questionnaire."}`,
  )
  .join("\n\n")}

\bibliographystyle{IEEEtran}
\bibliography{references}
\end{document}`;
}

// AI-based questionnaire answer enhancer
export async function enhanceAnswersWithAI(
  answers: Record<string, string>,
  questions: Question[],
  project: Project
): Promise<Record<string, string>> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "https://reportai-ytsn.onrender.com/api/v1";
  try {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };
    const apiKey = getOpenAiApiKey();
    if (apiKey) {
      headers["X-OpenAI-API-Key"] = apiKey;
    }

    const response = await fetch(`${API_URL}/generation/enhance-answers-public`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        project: {
          title: project.title,
          domain: project.domain,
          description: project.description,
        },
        answers,
        questions: questions.map((q) => ({ id: q.id, label: q.label, type: q.type })),
      }),
    });

    if (!response.ok) {
      throw new Error(`Backend enhancement returned status ${response.status}`);
    }

    const nextAnswers = await response.json();
    return nextAnswers;
  } catch (error) {
    console.error("Error enhancing answers with AI:", error);
    const nextAnswers = { ...answers };
    for (const key of Object.keys(answers)) {
      if (isNilAnswer(answers[key])) {
        nextAnswers[key] = "";
      }
    }
    return nextAnswers;
  }
}

// AI-based Dynamic LaTeX generator
export async function generateLatexWithAI(
  project: Project,
  answers: Record<string, string>,
  questions: Question[],
  templateProfile?: { chapters?: string[]; citation?: string; font?: string; spacing?: string }
): Promise<string> {
  const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "https://reportai-ytsn.onrender.com/api/v1";
  try {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
    };
    const apiKey = getOpenAiApiKey();
    if (apiKey) {
      headers["X-OpenAI-API-Key"] = apiKey;
    }

    const response = await fetch(`${API_URL}/generation/generate-report-public`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        project: {
          title: project.title,
          domain: project.domain,
          description: project.description,
        },
        answers,
        questions: questions.map((q) => ({ id: q.id, label: q.label, type: q.type })),
        templateProfile,
      }),
    });

    if (!response.ok) {
      throw new Error(`Backend LaTeX generation returned status ${response.status}`);
    }

    const data = await response.json();
    return data.latex;
  } catch (error) {
    console.error("Error generating LaTeX report with AI, falling back to static template:", error);
    return generateLatex(project, answers);
  }
}


export function analyzeQuality(latex: string, referenceCount: number): QualityScore {
  const wordCount = latex.split(/\s+/).filter(Boolean).length;
  const technicalDepth = Math.min(95, Math.max(45, Math.round(wordCount / 25)));
  const citationQuality = referenceCount > 0 ? 86 : 45;
  const formattingQuality = latex.includes("\\chapter") && latex.includes("\\tableofcontents") ? 90 : 58;
  const grammar = 84;
  const readability = 82;
  const overall = Math.round((technicalDepth + citationQuality + formattingQuality + grammar + readability) / 5);
  const suggestions = [];

  if (wordCount < 2500) suggestions.push("Expand methodology, testing, implementation, and result analysis.");
  if (referenceCount === 0) suggestions.push("Add academic references and cite them inside chapters.");
  if (!latex.includes("\\includegraphics")) suggestions.push("Add UML, flowchart, architecture, or result diagrams.");

  return {
    grammar,
    readability,
    technical_depth: technicalDepth,
    formatting_quality: formattingQuality,
    citation_quality: citationQuality,
    overall,
    suggestions,
  };
}
